<?xml version="1.0" encoding="utf-8"?><Database Name="LandBank" Class="PrDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Function Name="dbo.GetStatus" Method="GetStatus">
    <Parameter Name="StatusType" Parameter="statusType" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetStatusResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAssets" Method="GetAssets">
    <ElementType Name="GetAssetsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCities" Method="GetCities">
    <ElementType Name="GetCitiesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDistrictByCityId" Method="GetDistrictByCityId">
    <Parameter Name="CityId" Parameter="cityId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetDistrictByCityIdResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>