<?xml version="1.0" encoding="utf-8"?><Database Name="LandBank" Class="PrDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Function Name="dbo.GetStatus" Method="GetStatus">
    <Parameter Name="StatusType" Parameter="statusType" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetStatusResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>