<?xml version="1.0" encoding="utf-8"?><Database Name="LandBank" Class="PrDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Function Name="dbo.GetStatus" Method="GetStatus">
    <Parameter Name="StatusType" Parameter="statusType" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetStatusResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCities" Method="GetCities">
    <ElementType Name="GetCitiesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDistrictByCityId" Method="GetDistrictByCityId">
    <Parameter Name="CityId" Parameter="cityId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetDistrictByCityIdResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAssetNames" Method="GetAssetNames">
    <ElementType Name="GetAssetNamesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetLandUses" Method="GetLandUses">
    <Parameter Name="StatusType" Parameter="statusType" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="GetLandUsesResult">
      <Column Name="[JSON_F52E2B61-18A1-11d1-B105-00805F49916B]" Member="JSON_F52E2B61_18A1_11d1_B105_00805F49916B" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UserLogin" Method="UserLogin">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(255)" />
    <ElementType Name="UserLoginResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdId" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="JobTitle" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddBuyerDetails" Method="AddBuyerDetails">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BuyerName" Parameter="buyerName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CompanyId" Parameter="companyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Mobile" Parameter="mobile" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="AddBuyerDetailsResult">
      <Column Name="NewBuyerId" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetbuyerDetails" Method="GetbuyerDetails">
    <Parameter Name="Search" Parameter="search" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetbuyerDetailsResult">
      <Column Name="BuyerId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BuyerName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyNameEn" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateLandOverview" Method="UpdateLandOverview">
    <Parameter Name="LandId" Parameter="landId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Action" Parameter="action" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LandInformation" Parameter="landInformation" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Area" Parameter="area" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="SubAssetID" Parameter="subAssetID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Location" Parameter="location" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="MapImageURL" Parameter="mapImageURL" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="BusinessPlanID" Parameter="businessPlanID" Type="System.Int32" DbType="Int" />
    <Parameter Name="BusinessPlanDetailedID" Parameter="businessPlanDetailedID" Type="System.Int32" DbType="Int" />
    <Parameter Name="BusinessPlanStatusID" Parameter="businessPlanStatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LandStatusID" Parameter="landStatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LandUseId" Parameter="landUseId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LandTypeID" Parameter="landTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="WLTStatusID" Parameter="wLTStatusID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MunHandingOver" Parameter="munHandingOver" Type="System.Int32" DbType="Int" />
    <Parameter Name="Masterplan" Parameter="masterplan" Type="System.Int32" DbType="Int" />
    <Parameter Name="InfraApproval" Parameter="infraApproval" Type="System.Int32" DbType="Int" />
    <Parameter Name="InfraConstruction" Parameter="infraConstruction" Type="System.Int32" DbType="Int" />
    <Parameter Name="TitleDeedId" Parameter="titleDeedId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TitleDeedNo" Parameter="titleDeedNo" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="TitleDeedDate" Parameter="titleDeedDate" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="TitleDeedType" Parameter="titleDeedType" Type="System.Int32" DbType="Int" />
    <Parameter Name="TitleDeedStatus" Parameter="titleDeedStatus" Type="System.Int32" DbType="Int" />
    <Parameter Name="TDFileUrl" Parameter="tDFileUrl" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="TDOwnerID" Parameter="tDOwnerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DeedSequence" Parameter="deedSequence" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpsertBuyerDetails" Method="UpsertBuyerDetails" IsComposable="true">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Id" Parameter="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="BuyerId" Parameter="buyerId" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="BuyerName" Parameter="buyerName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CompanyId" Parameter="companyId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Mobile" Parameter="mobile" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.GetLandDetailsFilters2" Method="GetLandDetailsFilters2">
    <Parameter Name="LandId" Parameter="landId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Deptt" Parameter="deptt" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetLandDetailsFilters2Result">
      <Column Name="LandId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LandInformation" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="MapImageURL" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="PlotNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BusinessPlanDetails" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BusinessPlanName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="BusinessPlanStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandUse" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TDNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TDType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TitleDeedStatus" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TDDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TDOwnership" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WLTStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Column Name="ReferenceNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MasterPlan" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="InfraApproval" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="InfraContraction" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MHandingOver" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TitleDeeds" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Sales" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Finance" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Wlt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetLandCoordinates" Method="GetLandCoordinates">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LandId" Parameter="landId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetLandCoordinatesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LandId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(9,6)" CanBeNull="true" />
      <Column Name="LandShapeArray" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAssetsWithLandCount" Method="GetAssetsWithLandCount">
    <Parameter Name="SearchText" Parameter="searchText" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CityId" Parameter="cityId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AssetId" Parameter="assetId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAssetsWithLandCountResult">
      <Column Name="AssetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NumberOfLands" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalLandArea" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetLandByAssetId" Method="GetLandByAssetId">
    <Parameter Name="AssetId" Parameter="assetId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SearchText" Parameter="searchText" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CityId" Parameter="cityId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="OwnerId" Parameter="ownerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LandUseId" Parameter="landUseId" Type="System.Int32" DbType="Int" />
    <Parameter Name="BusinessPlanId" Parameter="businessPlanId" Type="System.Int32" DbType="Int" />
    <Parameter Name="WLTStatus" Parameter="wLTStatus" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetLandByAssetIdResult">
      <Column Name="LandId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LandStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandUse" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LandDeed" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BusinessPlan" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DeedOwner" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsWlt" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TitleDeedStatus" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RandomNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReferenceNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RowNum" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Valuation" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetLandDetailsFilters" Method="GetLandDetailsFilters">
    <Parameter Name="LandId" Parameter="landId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Deptt" Parameter="deptt" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetLandDetailsFiltersResult">
      <Column Name="LandId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LandInformation" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="MapImageURL" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="PlotNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BusinessPlanDetails" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BusinessPlanName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="BusinessPlanStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandUse" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TDNo" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TDType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TitleDeedStatus" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TDDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TDOwnership" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WLTStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(18,9)" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(18,9)" CanBeNull="true" />
      <Column Name="ReferenceNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MasterPlan" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="InfraApproval" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="InfraContraction" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MHandingOver" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TitleDeeds" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Sales" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Finance" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Wlt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.AddORUpdateLandCoordinates" Method="AddORUpdateLandCoordinates">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LandId" Parameter="landId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Latitude" Parameter="latitude" Type="System.Decimal" DbType="Decimal(18,9)" />
    <Parameter Name="Longitude" Parameter="longitude" Type="System.Decimal" DbType="Decimal(18,9)" />
    <Parameter Name="LandShapeWKT" Parameter="landShapeWKT" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpsertFinance" Method="UpsertFinance">
    <Parameter Name="LandId" Parameter="landId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Values" Parameter="values" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="ConsultantId" Parameter="consultantId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="TypeIds" Parameter="typeIds" Type="System.String" DbType="VarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
</Database>