//// <auto-generated />
//using System;
//using DataContext;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace DataContext.Migrations
//{
//    [DbContext(typeof(LBDbContext))]
//    [Migration("20240819165832_TablesAdded")]
//    partial class TablesAdded
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.14")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("Models.Models.Asset.AssetMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("AssetCode")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("AssetName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.HasKey("Id");

//                    b.ToTable("AssetMaster");
//                });

//            modelBuilder.Entity("Models.Models.Asset.SubAssetMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.Property<string>("SubAssetCode")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("SubAssetName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("SubAssetMaster");
//                });

//            modelBuilder.Entity("Models.Models.BusinessPlan.BusinessPlanMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("BusinessPlanName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.HasKey("Id");

//                    b.ToTable("BusinessPlanMaster");
//                });

//            modelBuilder.Entity("Models.Models.BusinessPlan.BusinessPlanStatusMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("BusinessPlanStatus")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.HasKey("Id");

//                    b.ToTable("BusinessPlanStatusMaster");
//                });

//            modelBuilder.Entity("Models.Models.Land.LandMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<decimal>("Area")
//                        .HasColumnType("decimal(18, 4)");

//                    b.Property<string>("BusinessPlanDetailed")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("DistrictId")
//                        .HasColumnType("int");

//                    b.Property<string>("LandInformation")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("LandStatusId")
//                        .HasColumnType("int");

//                    b.Property<int>("LandTypeId")
//                        .HasColumnType("int");

//                    b.Property<int>("LandUseId")
//                        .HasColumnType("int");

//                    b.Property<string>("Location")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("SubAssetId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("LandMaster");
//                });

//            modelBuilder.Entity("Models.Models.Land.LandStatusMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.Property<string>("LandStatus")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("LandStatusMaster");
//                });

//            modelBuilder.Entity("Models.Models.Land.LandTypeMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.Property<string>("LandType")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("ParentId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("LandTypeMaster");
//                });

//            modelBuilder.Entity("Models.Models.Land.LandUseMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.Property<string>("LandUse")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("ParentId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("LandUseMaster");
//                });

//            modelBuilder.Entity("Models.Models.Region.CityMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CityId")
//                        .HasColumnType("int");

//                    b.Property<string>("Code")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.Property<string>("NameAr")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("NameEn")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("RegionId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("CityMaster");
//                });

//            modelBuilder.Entity("Models.Models.Region.DistrictMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CityId")
//                        .HasColumnType("int");

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("DistrictId")
//                        .HasColumnType("int");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.Property<string>("NameAr")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("NameEn")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("RegionId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("DistrictMaster");
//                });

//            modelBuilder.Entity("Models.Models.Region.RegionMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CapitalCityId")
//                        .HasColumnType("int");

//                    b.Property<string>("Code")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.Property<string>("NameAr")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("NameEn")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("RegionId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("RegionMaster");
//                });

//            modelBuilder.Entity("Models.Models.WorkFlow.WF_ActionMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("ActionName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("WF_ActionMaster");
//                });

//            modelBuilder.Entity("Models.Models.WorkFlow.WF_ControlMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("ActionId")
//                        .HasColumnType("int");

//                    b.Property<int>("CurrentStage")
//                        .HasColumnType("int");

//                    b.Property<int>("NextStage")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("WF_ControlMaster");
//                });

//            modelBuilder.Entity("Models.Models.WorkFlow.WF_InstanceMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("CurrentStageId")
//                        .HasColumnType("int");

//                    b.Property<int>("InstanceId")
//                        .HasColumnType("int");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.HasKey("Id");

//                    b.ToTable("WF_InstanceMaster");
//                });

//            modelBuilder.Entity("Models.Models.WorkFlow.WF_ProcessMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.Property<string>("ProcessNameAr")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ProcessNameEn")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("WF_ProcessMaster");
//                });

//            modelBuilder.Entity("Models.Models.WorkFlow.WF_StageMaster", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("CreatedBy")
//                        .HasColumnType("int");

//                    b.Property<string>("CreatedFrom")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedOn")
//                        .HasColumnType("datetime2");

//                    b.Property<bool>("IsActive")
//                        .HasColumnType("bit");

//                    b.Property<int>("ProcessId")
//                        .HasColumnType("int");

//                    b.Property<string>("StageName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("WF_StageMaster");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
